
spring:
  cloud:
    gcp:
      project-id: projecttest-325212
      topic-name: projects/projecttest-325212/topics/test-topic
      credentials:
        location: classpath:projecttest-325212-33870e343e5e.json   # https://lemontia.tistory.com/961
