// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/example/pubsubstudy/pubsub/schema/singlemessage.proto

package com.example.pubsubstudy.pubsub.schema;

public interface SingleMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pubsubstudy.SingleMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string pushType = 1;</code>
   * @return Whether the pushType field is set.
   */
  boolean hasPushType();
  /**
   * <code>required string pushType = 1;</code>
   * @return The pushType.
   */
  java.lang.String getPushType();
  /**
   * <code>required string pushType = 1;</code>
   * @return The bytes for pushType.
   */
  com.google.protobuf.ByteString
      getPushTypeBytes();

  /**
   * <code>required string token = 2;</code>
   * @return Whether the token field is set.
   */
  boolean hasToken();
  /**
   * <code>required string token = 2;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>required string token = 2;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>required string title = 3;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>required string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>required string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>required string body = 4;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <code>required string body = 4;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>required string body = 4;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
